import { Footer, GetStarted, Help, RegisterSection } from "@/components/Home";
import HeroSection from "@/components/Home/HeroSection";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Vaccine Management</title>
        <meta name="description" content="Generated by vaccine Management" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <Help />
      <GetStarted />
      <RegisterSection />
      <Footer />
    </>
  );
}

